### PR TITLE
Build and publish a debian package

### PR DESCRIPTION
**Pull request by skullydazed**
## Description

When a new version is published also create a signed debian package and upload it to an S3 bucket.

### CODE REVIEW

**Comment by skullydazed** [comment]
I've zipped up the repo directory generated by running the workflow commands manually here, this is what I expect the eventual structure of https://debian.qmk.fm/ to look like.

[qmk_debian_repo.zip](https://github.com/qmk/qmk_cli/files/6934345/qmk_debian_repo.zip)

**Comment by skullydazed** [comment]
I've uploaded the contents of that zip file to spaces so that you can test the debian side of it now:

```
curl https://debian.qmk.fm/gpg_pubkey.txt | sudo apt-key add -
echo 'deb https://debian.qmk.fm/ /' >> /etc/apt/sources.list
sudo apt update
```

**Comment by Foxboron** [comment]
Instead of duplicating the udev rules I'd rename `debian/50-qmk.rules` -> `udev/50-qmk.rules` and rm the rules from the firmware repository. Point the documentation to the file in this repo instead and make this repo the canonical source.

**Comment by skullydazed** [comment]
> Instead of duplicating the udev rules I'd rename `debian/50-qmk.rules` -> `udev/50-qmk.rules` and rm the rules from the firmware repository. Point the documentation to the file in this repo instead and make this repo the canonical source.

I actually ended up creating a new repo for this package- [qmk/qmk_fpm](/qmk/qmk_fpm)

I agree that we want one source of truth for the rules file. I don't know the best way to do that yet, as we need to supply that file to multiple linux distributions, not just debian. Ideally we will use fpm to build packages for everything we support, but I don't think that's going to pan out for all distributions.

**Pull request closed without merging**
