### PR TITLE
read README with utf-8 and close file after reading

### PR DESCRIPTION
**Pull request by StrikerRUS**

### CODE REVIEW

**Comment by skullydazed** [comment]
Thanks!

**Comment by StrikerRUS** [comment]
@skullydazed You are welcome! Did I understand correctly, this PR is not counted towards Hacktoberfest interaction, right?

**Comment by skullydazed** [comment]
I believe you are correct, but I've seen other contributions from you that do count.

**Comment by StrikerRUS** [comment]
@skullydazed OK, got it!

**Pull request merged**
